"""Create mood entry table

Revision ID: 252dfd917a27
Revises: a540976f0330
Create Date: 2025-11-02 19:18:31.888438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '252dfd917a27'
down_revision: Union[str, Sequence[str], None] = 'a540976f0330'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mood_entry',
    sa.Column('score', sa.SmallInteger(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('for_me', 'only_friends', 'only_user', 'only_friend_excluded_user', 'for_all_excluded_user', 'for_all', name='mood_publish_status_enum'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mood_entry_id'), 'mood_entry', ['id'], unique=False)
    op.create_index(op.f('ix_mood_entry_status'), 'mood_entry', ['status'], unique=False)
    op.create_index(op.f('ix_mood_entry_user_id'), 'mood_entry', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mood_entry_user_id'), table_name='mood_entry')
    op.drop_index(op.f('ix_mood_entry_status'), table_name='mood_entry')
    op.drop_index(op.f('ix_mood_entry_id'), table_name='mood_entry')
    op.drop_table('mood_entry')
    # ### end Alembic commands ###
