"""Create friendship table

Revision ID: 47bac66ea26e
Revises: 904298d2b6af
Create Date: 2025-11-02 16:26:52.750681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47bac66ea26e'
down_revision: Union[str, Sequence[str], None] = '904298d2b6af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friend_ship',
    sa.Column('sender_request_user_id', sa.Integer(), nullable=False),
    sa.Column('recipient_request_user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', name='friend_ship_status_enum'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['recipient_request_user_id'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_request_user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_friend_ship_id'), 'friend_ship', ['id'], unique=False)
    op.create_index(op.f('ix_friend_ship_recipient_request_user_id'), 'friend_ship', ['recipient_request_user_id'], unique=True)
    op.create_index(op.f('ix_friend_ship_sender_request_user_id'), 'friend_ship', ['sender_request_user_id'], unique=True)
    op.create_index(op.f('ix_friend_ship_status'), 'friend_ship', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_friend_ship_status'), table_name='friend_ship')
    op.drop_index(op.f('ix_friend_ship_sender_request_user_id'), table_name='friend_ship')
    op.drop_index(op.f('ix_friend_ship_recipient_request_user_id'), table_name='friend_ship')
    op.drop_index(op.f('ix_friend_ship_id'), table_name='friend_ship')
    op.drop_table('friend_ship')
    # ### end Alembic commands ###
