"""Create contact table

Revision ID: 904298d2b6af
Revises: b279b37e3d62
Create Date: 2025-11-02 16:11:03.370416

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "904298d2b6af"
down_revision: Union[str, Sequence[str], None] = "b279b37e3d62"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "contact",
        sa.Column("value", sa.String(length=50), nullable=False),
        sa.Column(
            "type",
            sa.Enum("0", "1", "2", "3", "4", "5", "6", "7", name="contact_type_enum"),
            nullable=False,
        ),
        sa.Column("other_type", sa.String(length=50), nullable=True),
        sa.Column("verified_at", sa.DateTime(), nullable=False),
        sa.Column("deactivated_at", sa.DateTime(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_contact_id"), "contact", ["id"], unique=False)
    op.create_index(op.f("ix_contact_type"), "contact", ["type"], unique=False)
    op.create_index(op.f("ix_contact_user_id"), "contact", ["user_id"], unique=True)
    op.create_index(op.f("ix_contact_value"), "contact", ["value"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_contact_value"), table_name="contact")
    op.drop_index(op.f("ix_contact_user_id"), table_name="contact")
    op.drop_index(op.f("ix_contact_type"), table_name="contact")
    op.drop_index(op.f("ix_contact_id"), table_name="contact")
    op.drop_table("contact")
    # ### end Alembic commands ###
