"""Create user setting table

Revision ID: 9088a8d5d42c
Revises: 2e989ea635a2
Create Date: 2025-11-02 18:47:33.108460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9088a8d5d42c'
down_revision: Union[str, Sequence[str], None] = '2e989ea635a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_setting',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('value', sa.String(length=50), nullable=False),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_setting_id'), 'user_setting', ['id'], unique=False)
    op.create_index(op.f('ix_user_setting_name'), 'user_setting', ['name'], unique=False)
    op.create_index(op.f('ix_user_setting_user_id'), 'user_setting', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_setting_user_id'), table_name='user_setting')
    op.drop_index(op.f('ix_user_setting_name'), table_name='user_setting')
    op.drop_index(op.f('ix_user_setting_id'), table_name='user_setting')
    op.drop_table('user_setting')
    # ### end Alembic commands ###
