"""Create mood entry tag table

Revision ID: 9d531ee4045f
Revises: 252dfd917a27
Create Date: 2025-11-02 19:22:26.578791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d531ee4045f'
down_revision: Union[str, Sequence[str], None] = '252dfd917a27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mood_entry_tags',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mood_entry_tags_id'), 'mood_entry_tags', ['id'], unique=False)
    op.create_index(op.f('ix_mood_entry_tags_tag_id'), 'mood_entry_tags', ['tag_id'], unique=False)
    op.create_index(op.f('ix_mood_entry_tags_user_id'), 'mood_entry_tags', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mood_entry_tags_user_id'), table_name='mood_entry_tags')
    op.drop_index(op.f('ix_mood_entry_tags_tag_id'), table_name='mood_entry_tags')
    op.drop_index(op.f('ix_mood_entry_tags_id'), table_name='mood_entry_tags')
    op.drop_table('mood_entry_tags')
    # ### end Alembic commands ###
