"""Create access data table

Revision ID: b279b37e3d62
Revises: fc8e0abae3a0
Create Date: 2025-11-02 15:17:37.551765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b279b37e3d62'
down_revision: Union[str, Sequence[str], None] = 'fc8e0abae3a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_data',
    sa.Column('login', sa.String(length=20), nullable=False),
    sa.Column('hashed_password', sa.Text(), nullable=False),
    sa.Column('deactivated_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_access_data_id'), 'access_data', ['id'], unique=False)
    op.create_index(op.f('ix_access_data_login'), 'access_data', ['login'], unique=True)
    op.create_index(op.f('ix_access_data_user_id'), 'access_data', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_access_data_user_id'), table_name='access_data')
    op.drop_index(op.f('ix_access_data_login'), table_name='access_data')
    op.drop_index(op.f('ix_access_data_id'), table_name='access_data')
    op.drop_table('access_data')
    # ### end Alembic commands ###
