"""Create mood entry visibility table

Revision ID: c1481f006401
Revises: 9d531ee4045f
Create Date: 2025-11-02 19:31:00.574559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1481f006401'
down_revision: Union[str, Sequence[str], None] = '9d531ee4045f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mood_entry_visibility',
    sa.Column('mood_entry_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('for_me', 'only_friends', 'only_user', 'only_friend_excluded_user', 'for_all_excluded_user', 'for_all', name='mood_visibility_status_enum'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['mood_entry_id'], ['mood_entry.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mood_entry_visibility_id'), 'mood_entry_visibility', ['id'], unique=False)
    op.create_index(op.f('ix_mood_entry_visibility_mood_entry_id'), 'mood_entry_visibility', ['mood_entry_id'], unique=False)
    op.create_index(op.f('ix_mood_entry_visibility_status'), 'mood_entry_visibility', ['status'], unique=False)
    op.create_index(op.f('ix_mood_entry_visibility_user_id'), 'mood_entry_visibility', ['user_id'], unique=False)
    op.add_column('mood_entry_tags', sa.Column('mood_entry_id', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_mood_entry_tags_user_id'), table_name='mood_entry_tags')
    op.create_index(op.f('ix_mood_entry_tags_mood_entry_id'), 'mood_entry_tags', ['mood_entry_id'], unique=False)
    op.drop_constraint(op.f('mood_entry_tags_user_id_fkey'), 'mood_entry_tags', type_='foreignkey')
    op.create_foreign_key(None, 'mood_entry_tags', 'mood_entry', ['mood_entry_id'], ['id'], ondelete='CASCADE')
    op.drop_column('mood_entry_tags', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mood_entry_tags', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'mood_entry_tags', type_='foreignkey')
    op.create_foreign_key(op.f('mood_entry_tags_user_id_fkey'), 'mood_entry_tags', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_mood_entry_tags_mood_entry_id'), table_name='mood_entry_tags')
    op.create_index(op.f('ix_mood_entry_tags_user_id'), 'mood_entry_tags', ['user_id'], unique=False)
    op.drop_column('mood_entry_tags', 'mood_entry_id')
    op.drop_index(op.f('ix_mood_entry_visibility_user_id'), table_name='mood_entry_visibility')
    op.drop_index(op.f('ix_mood_entry_visibility_status'), table_name='mood_entry_visibility')
    op.drop_index(op.f('ix_mood_entry_visibility_mood_entry_id'), table_name='mood_entry_visibility')
    op.drop_index(op.f('ix_mood_entry_visibility_id'), table_name='mood_entry_visibility')
    op.drop_table('mood_entry_visibility')
    # ### end Alembic commands ###
